name: Pylint_django

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          shopt -s globstar && pylint --load-plugins pylint_django --django-settings-module=example.settings **/*.py